package br.projeto.lab.Enums;

public enum Permissao {
    GERENCIAR_CURRICULO,
    GERENCIAR_DISCIPLINAS,
    GERENCIAR_PROFESSORES,
    GERENCIAR_ALUNOS,
    DEFINIR_PERIODO_MATRICULA,
    MATRICULAR_DISCIPLINA,
    CANCELAR_MATRICULA,
    VISUALIZAR_MATRICULAS
}